Ept 1715 create page modal v2
sailthru/hosted-pages-frontend pull request #12
Opened 2022-12-22 20:39 UTC by shanthru

2023-01-04 00:36 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +    }
thoughts / suggestions:
- (non-blocking) The variables `allowDashInName` and `alphanumericRegex` initially confused me because of their location at the top of the method. I thought they were needed for the entire method because of this placement. I'd suggest moving that logic closer to where it is used (right above the if-statement)
- (blocking / question) The variable `allowDashInName` name confused because I was expecting it to be a boolean value when its actually a new name variable. I think you are using it to check for alphanumeric characters after dashes have been removed. I'd suggest that you write one regular expression that checks for all valid characters (see suggestion below). Is there are problem with this approach? Are dashes only allowed in certain places?
- (blocking) The error message should match the explainer text from the ticket (see suggest below).

```suggestion
    if (name.length < 1) {
      setNamingError("Please enter a page name.");
      return;
    }
    
    const allowedCharactersRegex = /^[a-zA-Z0-9-]+$/; // only alphanumeric characters and dashes allowed
    if (!name.match(allowedCharactersRegex)) {
      setNamingError("Page names can only contain alphanumeric characters and dashes.");
      return;
    }
```

2023-01-04 00:37 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +        "The page name 'oc' is a reserved page name. Please select a new page name."
nit-pick
```suggestion
        "The name 'oc' is a reserved page name. Please use a different page name."
```

2023-01-04 00:38 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +    setNamingError("");
question: Should `setOptoutNamingError` also be reset here?

2023-01-04 00:39 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +    setOptoutNamingError(false);
question: In the beginning of this method, the parameter used for `setNamingError` is an empty string. Why is a boolean value being used here?
```suggestion
    setNamingError("");
    setOptoutNamingError("");
```

2023-01-04 00:39 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +    setOptoutNamingError(false);
question: If this is being done at the top of the method, why does it need to be done again here?

2023-01-04 00:40 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +    if (name == "optout") {
nit-pick: I think this should be a `===`
```suggestion
    if (name === "optout") {
```

2023-01-04 00:41 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +    }
nit-pick (non-blocking): These simpler checks could be moved higher up in the method. I'd suggest the order: length check, reserved name check, regex check

2023-01-04 00:42 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +  useEffect(() => {
nit-pick: I think your code explains this well enough without the comment (good variable names below 👍 )
```suggestion
  useEffect(() => {
```

2023-01-04 00:43 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +      setNamingError(false);
question (same as above): Should this be an empty string instead?

2023-01-04 00:43 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +  const onChangeResetNamingError = (e) => {
nit-pick: I think your code explains this well enough without the comment (good function name 👍 )
```suggestion
  const onChangeResetNamingError = (e) => {
```

2023-01-04 00:44 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +  const handleNamingError = function () {
nit-pick: I think your code explains this well enough without the comment
```suggestion
  const handleNamingError = function () {
```

2023-01-04 00:45 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +          onBlur={handleNamingError}
nit-pick (non-blocking): 
```suggestion
          onBlur={determineNamingError}
```

2023-01-04 00:52 UTC, lindsaycooper reviewed
@shanthru This might make more sense to chat in person about:
I think the directory structure here is a bit confusing.
- What belongs in the `feature` subdirectory?
- What belongs in `core`?
- What belongs in `src` (no sub-directory)?

2023-01-04 15:43 UTC, shanthru commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +        "The page name 'oc' is a reserved page name. Please select a new page name."
updated

2023-01-04 22:47 UTC, lindsaycooper requested changes

2023-01-04 22:47 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageModal.jsx
> +          console.log("An error occurred redirecting to the new page");
suggestion: Add more helpful debugging information here:
```suggestion
          console.error(`Error redirecting to page origin:${window.location.origin}, url:${response._data.editor_url}`);
          
```

2023-01-04 22:47 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageModal.jsx
> +          serverErrorMessage.includes(duplicateNameError)
nit-pick: I don't think the variable name helps with clarity here
```suggestion
        let serverErrorMessage = serverError.error_message;
        if (
          serverErrorMessage &&
          serverErrorMessage.includes("There is already a page named")
```

2023-01-04 22:47 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageModal.jsx
> +          console.log("ERROR: ", serverError.error_message);
```suggestion
          console.error("ERROR: ", serverErrorMessage);
```

2023-01-04 22:47 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageModal.jsx
> +          setIsDuplicateName("Unique page name required.");
suggestion: Elsewhere in this file `setIsDuplicateName` uses booleans instead of strings. I think this makes sense. This error message can be moved to where it's displayed.
```suggestion
          setIsDuplicateName(true);
```

2023-01-04 22:47 UTC, lindsaycooper commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +      setNamingError(isDuplicateName);
```suggestion
      setNamingError("Unique page name required.");
```

2023-01-04 23:00 UTC, lindsaycooper requested changes

2023-01-04 23:00 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +        "Page names can only contain alphanumeric characters and dashes."
nit-pick: Trying to better match the other error message:
```suggestion
        "The page name must only contain alphanumeric characters and dashes. Please use a different page name."
```

2023-01-04 23:00 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +      setNamingError(isDuplicateName);
```suggestion
      setNamingError("The page name must be unique. Please use a different page name.");
```

2023-01-04 23:00 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +          onChange={onChangeResetNamingError}
suggestion: This does more than reset the naming error
```suggestion
          onChange={onChangeHandler}
```

2023-01-04 23:00 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    }
```suggestion
  const onChangeHandler = (e) => {
    if (isNameChanged) {
      setNamingError("");
      setOptoutNamingError("");
    }
```

2023-01-04 23:00 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageModal.jsx
> +          setError("Something went wrong and we could not load the page.");
suggestion: `setError` should not use both booleans and strings
```suggestion
          setError(true);
```

2023-01-04 23:00 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageModal.jsx
> +          );
```suggestion
          setError(true);
```

2023-01-04 23:00 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageModal.jsx
> +      {error && <Notification type="error">{error}</Notification>}
```suggestion
      {error && 
          <Notification type="error">
              An error occurred creating the page. Please try again or contact support if the issue persists.
          </Notification>}
```

2023-01-05 13:24 UTC, shanthru commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +    if (name == "optout") {
updated

2023-01-05 21:03 UTC, shanthru commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +    }
updated

2023-01-05 21:04 UTC, shanthru commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +      setNamingError(false);
updated

2023-01-05 21:05 UTC, shanthru commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +          onBlur={handleNamingError}
changed to checkForNamingError

2023-01-05 21:05 UTC, shanthru commented on src/ListView/features/CreatePage/CreatePageModal.jsx
> +          console.log("An error occurred redirecting to the new page");
updated

2023-01-05 21:05 UTC, shanthru commented on src/ListView/features/CreatePage/CreatePageModal.jsx
> +          serverErrorMessage.includes(duplicateNameError)
removed this variable

2023-01-05 21:06 UTC, shanthru commented on src/ListView/features/CreatePage/CreatePageForm.jsx
> +      setNamingError(isDuplicateName);
updated

2023-01-05 21:06 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +        "Page names can only contain alphanumeric characters and dashes."
updated

2023-01-05 21:07 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +      setNamingError(isDuplicateName);
updated

2023-01-05 21:07 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +          onChange={onChangeResetNamingError}
updated

2023-01-05 21:07 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    }
updated

2023-01-05 21:07 UTC, shanthru commented on src/ListView/CreatePage/CreatePageModal.jsx
> +          setError("Something went wrong and we could not load the page.");
updated everything to string

2023-01-05 21:08 UTC, shanthru commented on src/ListView/CreatePage/CreatePageModal.jsx
> +          );
updated everything to string

2023-01-05 21:08 UTC, shanthru commented on src/ListView/CreatePage/CreatePageModal.jsx
> +      {error && <Notification type="error">{error}</Notification>}
updated everything to string

2023-01-05 23:54 UTC, lindsaycooper reviewed
A few nit-picks

2023-01-05 23:54 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +  const checkForNamingError = function () {
```suggestion
  const checkForNamingError = function () {
```

2023-01-05 23:54 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +  useEffect(() => {
```suggestion
  useEffect(() => {
```

2023-01-05 23:54 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +  const onChangeHandler = (e) => {
```suggestion
  const onChangeHandler = (e) => {
```

2023-01-05 23:54 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageModal.jsx
> +            `Error redirecting to page name:${JSON.stringify(response._data)}`
```suggestion
            `Error redirecting to page:${JSON.stringify(response._data)}`
```

2023-01-05 23:54 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageModal.jsx
> +            "An error occurred and the page could not be created. Please try again or contact support if the issue persists"
```suggestion
            "An error occurred and the page could not be created. Please try again or contact support if the issue persists."
```

2023-01-05 23:54 UTC, lindsaycooper approved these changes
LGTM

2023-01-06 00:31 UTC, lindsaycooper reviewed
### QA Steps

✅ Verify New Page button opens HTML modal to create a new page <img width="500" alt="image" src="https://user-images.githubusercontent.com/10618083/210902746-4c57daf9-765c-4ffa-9a2f-270cb0aaf7d8.png">
- ✅ Title of modal should read “New HTML Page”
- ✅ Page name explanation copy: `Page name must follow URL standards and only contain alphanumeric characters and dashes. It is recommended to use dashes instead of spaces.`
- ✅ Name field: Auto-focused on modal load
- ✅ Name field: Required for “Create” button to be clickable
- ✅ Name field: Verify “Create” button is **enabled** when name has 1 alphanumeric character (when Category selected)
- Name field: Verify “Create” button is disabled when name doesn’t have an alphanumeric character (when Category selected). Error message: `The page name must only contain alphanumeric characters and dashes. Please use a different page name.`
  - ✅ When the "Create" button has **not** previously been enabled the above is true
  - ✅ When the "Create" button has been enabled and then the name is removed, the above is true
  - ❌ When the "Create" button has been enabled and then a new invalid name is entered, the "Create" button is not disabled on error 
  <img width="500" alt="image" src="https://user-images.githubusercontent.com/10618083/210903298-202cd180-9fab-4d7b-a284-2f9e56a66907.png">

- ✅ Name field: Verify removing text from this field disables the button (when Category selected)
- ✅ Name field: Must be unique
- ✅ Name field:  Show error message under name when backend responds with 4xx error. Error Message: `The page name must be unique. Please use a different page name.`
- ✅ Category field: No buttons are selected on modal load
- ✅ Category field: Required for “Create” button to be clickable
- ✅ Category field: Verify “Create” button is **disabled** when no radio button selected (when Name field is valid)
- ✅ Category field: Verify “Create” button is **enabled** when radio button selected (when Name field is valid)

- ✅ Verify that when selecting “CANCEL” in the modal, modal is removed and returned back to List Page
- ✅ Verify that when selecting “X” in the modal, modal is removed and returned back to List Page

- ✅ Verify that when selecting “CREATE”  in the modal with valid name and category, redirected to HTML editor

@shanthru I think this error message should be updated to this: 
```The page name must contain at least one alphanumeric character and may contain dashes. Please use a different page name.```
 <img width="500" alt="image" src="https://user-images.githubusercontent.com/10618083/210903438-35ea9468-283c-41da-808f-40e84c86cc30.png">

2023-01-06 18:30 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +  const checkForNamingError = function () {
function comments have been removed

2023-01-06 18:30 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +  useEffect(() => {
function comments have been removed

2023-01-06 18:30 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +  const onChangeHandler = (e) => {
function comments have been removed

2023-01-06 18:30 UTC, shanthru commented on src/ListView/CreatePage/CreatePageModal.jsx
> +            "An error occurred and the page could not be created. Please try again or contact support if the issue persists"
updated

2023-01-06 18:32 UTC, shanthru commented
A change has been made to handle the failing test case.
I also noted one other UI display issue and implemented a change for that in a separate commit.

2023-01-06 18:40 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    setNamingError("");
question: Does `setIsValidName` need to be reset here too?
```suggestion
    setNamingError("");
    setIsValidName(true);
```

2023-01-06 19:32 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    setNamingError("");
yes, it should!

2023-01-06 19:34 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    setOptoutNamingError("");
question: Are these needed here since you are resetting them in `onChangeHandler`?

2023-01-06 19:36 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    }
I'm confused by this use case. Can you explain more why the space is needed? Why not put an actual error message? Does this negation do the same thing?
```suggestion
    if (name !== "optout") {
      setOptoutNamingError("");
    }
```

2023-01-06 19:58 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    }
yes it does!

2023-01-06 20:38 UTC, shanthru commented on package.json
> +    "@sailthru/stui-layouts": "1.0.5",
`stui-layouts` [latest](https://github.com/sailthru/stui-layouts/releases/tag/v1.0.5) version is 1.0.5
I had tried another version of `design-tokens` but had conflicts until I switched to this version.

2023-01-06 20:44 UTC, shanthru commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    setOptoutNamingError("");
good point...
I originally had these set here before implementing the `onChangeHandler` (some of our UIs do not reset the error until the next onBlur)
There isn't a negative impact on removing them but checking to see if there is any best practice to leave this.

2023-01-06 21:29 UTC, lindsaycooper commented on src/ListView/CreatePage/CreatePageForm.jsx
> +    setOptoutNamingError("");
I think this would fall under DRY principle - if it's only needed one place, only put it in one place

2023-01-06 22:57 UTC, lindsaycooper approved these changes
CR +1

2023-01-06 22:58 UTC, lindsaycooper approved these changes
#### QA +1

✅  Verify New Page button opens HTML modal to create a new page
- ✅ Title of modal should read “New HTML Page”
- ✅ Page name explanation copy: `Page name must follow URL standards and only contain alphanumeric characters and dashes. It is recommended to use dashes instead of spaces.`
- ✅ Name field: Auto-focused on modal load
- ✅ Name field: Required for “Create” button to be clickable
- ✅ Name field: Verify “Create” button is **enabled** when name has 1 alphanumeric character (when Category selected)
- ✅ Name field: Verify “Create” button is disabled when name doesn’t have an alphanumeric character (when Category selected). Error message: `The page name must contain at least one alphanumeric character and may contain dashes. Please use a different page name.`
  - ✅ When the "Create" button has **not** previously been enabled
  - ✅ When the "Create" button has been enabled and then the name is removed
  - ✅ When the "Create" button has been enabled and then a new invalid name is entered
- ✅ Name field: Verify removing text from this field disables the button (when Category selected)
- ✅ Name field: Must be unique. Show error message under name when existing page already loaded in the list. Error Message: `The page name must be unique. Please use a different page name.`
- ✅ Name field:  Show error message under name when backend responds with 4xx error. Error Message: `The page name must be unique. Please use a different page name.`

- ✅ Category field: No buttons are selected on modal load
- ✅ Category field: Required for “Create” button to be clickable
- ✅ Category field: Verify “Create” button is **disabled** when no radio button selected (when Name field is valid)
- ✅ Category field: Verify “Create” button is **enabled** when radio button selected (when Name field is valid)

- ✅ Verify that when selecting “CANCEL” in the modal, modal is removed and returned back to List Page
  **❓When there is an error (including empty name), the user has to click the cancel button twice. This behavior also happens in the modals on the Custom Fonts page so I'm ok with this not being a blocker**
- ✅ Verify that when selecting “X” in the modal, modal is removed and returned back to List Page

- ✅ Verify that when selecting “CREATE”  in the modal with valid name and category, redirected to HTML editor for page with that name & category
  - ✅ Verify that "Signup" category selected creates a page with type "signup"
  - ✅ Verify that "User Management" category selected creates a page with type "manage"
  - ✅ Verify that "Other" category selected creates a page with type "other"

- ✅ Edge Case with name "optout"
  1. Type "Test" in name field
  2. Select "other" or "signup" in the category field. Side effect: "Create" button enabled
  3. Type "optout" in name field
    - ✅ Subtext displays: `The page name 'optout' requires 'User Management' as the category. Please select 'User Management' below.` 
    - ✅ Radio buttons  "Signup" and "Other" are disabled
    - ✅ "Create" button is disabled

2023-01-09 15:02 UTC, merged