[EPT-1721] Add filtering sorting to hosted pages list page.
sailthru/hosted-pages-frontend pull request #15
Opened 2023-01-27 22:04 UTC by Andrew-Gaffney

EPT-1721: [https://sailthru.atlassian.net/browse/EPT-1721] 

Add filter sidebar to hosted pages list page that supports searching in the text input field and selection of multiple options for mode and type.

2023-01-27 22:46 UTC, lindsaycooper requested changes

2023-01-27 22:46 UTC, lindsaycooper commented on src/common/pagesApi.js
> +  return queryString ? http.get(`/uiapi/page?${queryString}`) : http.get("/uiapi/page");
nit-pick: This could be simplified using a [default parameter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters)
```suggestion
export function fetchPages(queryString = "") {
  return http.get(`/uiapi/page?${queryString}`);
```

2023-01-27 22:46 UTC, lindsaycooper commented on src/list/FilterSidebar.jsx
> +                    Mode
Blocking: Even though internally this is mode, externally (with customers) its supposed to be type
```suggestion
                    Type
```

2023-01-27 22:46 UTC, lindsaycooper commented on src/list/FilterSidebar.jsx
> +                ))}
Based on the [mock](https://whimsical.com/page-builder-v1-list-page-8BWsnwC679HfD5XMSRj7vd), this should look like the template list page (not actual checkboxes)

![image](https://user-images.githubusercontent.com/10618083/215220299-62a5c0cc-a1a5-4bb0-93de-c1cd3d95483e.png)

2023-01-27 22:46 UTC, lindsaycooper commented on src/list/FilterSidebar.jsx
> +                ))}
I think for V1 only HTML should be showing as well

2023-01-27 22:46 UTC, lindsaycooper commented on src/list/FilterSidebar.jsx
> +                    Type
Blocking: Even though internally this is type, externally (with customers) its supposed to be category
```suggestion
                    Category
```

2023-01-27 22:46 UTC, lindsaycooper commented on src/list/FilterSidebar.jsx
> +    const types = ['Signup', 'Manage', 'Other'];
The label for "manage" pages should be "User Management"

2023-01-27 22:46 UTC, lindsaycooper commented on src/list/ListView.jsx
> +        queryString += `name=${filterObject.name}`;
suggestion: Adding a trailing `&` could make the rest of the logic in this method more simple (and shouldn't have a negative side effect)
```suggestion
        queryString += `name=${filterObject.name}&`;
```

2023-01-27 22:46 UTC, lindsaycooper commented on src/list/ListView.jsx
> +        });
```suggestion
        filterObject.modes.forEach((mode) => {
            queryString += `modes=${mode}&`;
        });
```

2023-01-27 22:46 UTC, lindsaycooper commented on src/list/ListView.jsx
> +        })
```suggestion
    if(filterObject.types.length) {
        filterObject.types.forEach((type) => {
            queryString += `types=${type}&`;
        })
```

2023-01-28 00:35 UTC, Andrew-Gaffney commented on src/common/pagesApi.js
> +  return queryString ? http.get(`/uiapi/page?${queryString}`) : http.get("/uiapi/page");
It would make it simpler but the URL would always have the question mark present, is that ok?

2023-01-28 00:37 UTC, Andrew-Gaffney commented on src/common/pagesApi.js
> +  return queryString ? http.get(`/uiapi/page?${queryString}`) : http.get("/uiapi/page");
Never mind, forgot that this is just the request URL and isn't really client facing anyway.

2023-01-28 04:58 UTC, Andrew-Gaffney commented on src/common/pagesApi.js
> +  return queryString ? http.get(`/uiapi/page?${queryString}`) : http.get("/uiapi/page");
Suggestion taken.

2023-01-28 04:58 UTC, Andrew-Gaffney commented on src/list/FilterSidebar.jsx
> +                    Mode
Should be fixed.

2023-01-28 04:58 UTC, Andrew-Gaffney commented on src/list/FilterSidebar.jsx
> +                ))}
Should be resolved.

2023-01-28 04:58 UTC, Andrew-Gaffney commented on src/list/FilterSidebar.jsx
> +                    Type
Should be updated.

2023-01-28 04:59 UTC, Andrew-Gaffney commented on src/list/FilterSidebar.jsx
> +    const types = ['Signup', 'Manage', 'Other'];
Also fixed.

2023-01-28 04:59 UTC, Andrew-Gaffney commented on src/list/ListView.jsx
> +        queryString += `name=${filterObject.name}`;
Suggestion taken.

2023-01-28 05:00 UTC, Andrew-Gaffney commented on src/list/ListView.jsx
> +        });
Suggestion taken.

2023-01-28 05:00 UTC, Andrew-Gaffney commented on src/list/ListView.jsx
> +        })
Suggestion taken.

2023-01-31 17:24 UTC, shanthru commented on src/list/FilterSidebar.jsx
> +                    </ListRowContainer>
blocking: `{value} key={key}` within `ListRowContainer` causes an error and does not pass the mode. Move `{value} key={key}` to `ListRow`
```suggestion
<ListRowContainer >
                        <ListRow value={value} key={key} onClick={onClickMode}>
                            <i className="fal fa-code" title="HTML Page" />
                            &nbsp;{value}
                        </ListRow>
                    </ListRowContainer>
```

2023-01-31 17:28 UTC, shanthru commented on src/list/FilterSidebar.jsx
> +                    </ListRowContainer>
```suggestion
<ListRowContainer value={value} key={key}>
                        <ListRow value={value} key={key} onClick={onClickMode}>
                            <i className="fal fa-code" title="HTML Page" />
                            &nbsp;{value}
                        </ListRow>
                    </ListRowContainer>
```

2023-01-31 18:36 UTC, Andrew-Gaffney commented on src/list/FilterSidebar.jsx
> +                    </ListRowContainer>
Should be fixed now.

2023-01-31 23:13 UTC, shanthru commented
QA Steps:
     ✅ Sorting should work properly after pages have been filtered. Note. Client-side sorting

     ✅ Typing in the search box should return “loose matching” on the page name

     🚫 Removed from frontend for now: Clicking “HTML” type should only return HTML pages (all pages for now)

     ✅ Clicking “Sign up” category should only return signup pages

     ✅ Clicking “User management” category should only return manage pages

     ✅ Clicking “Other” category should only return other pages

     When more than one filter option is chosen:

          Filtering should return pages with all the criteria met (AND operations) for each section selected

              ✅ Category = "User Management" + Category = "Signup" should return all pages that are BOTH type:manage AND type:signup in the DB

           ✅ Name = "test" + Category = "Signup" should return all pages that are BOTH name contains:test AND type:signup in the DB

         ✅ Filtering should return pages with at least one of the criteria met (OR operations) within each section

              ✅ Category = Signup + Category = Other should return all pages that are EITHER type:signup OR type:other in the DB

2023-02-02 20:02 UTC, shanthru reviewed
QA+1

2023-02-02 22:04 UTC, lindsaycooper commented on src/list/FilterSidebar.jsx
> +        onChange({types: typeList, name: searchValue});
nit-pick: `typeList` vs `typesList` is hard to distinguish in the logic
```suggestion
        const typesFilter = [];
        newValue.forEach(value => {
            typesFilter.push(types[value]);
        })
        setTypesList(typesFilter);
        onChange({types: typesFilter, name: searchValue});
```

2023-02-02 22:07 UTC, lindsaycooper approved these changes

2023-02-03 20:25 UTC, lindsaycooper commented on src/list/FilterSidebar.jsx
> +    height: 100vh;
nit-pick: Adding width here will make "User management" stay on one line
```suggestion
    height: 100vh;
    width: 160px;
```

2023-02-03 22:02 UTC, merged